services:
  products:
    build: ./services/products
    container_name: products
    env_file:
      - .env
    ports:
      - '$BIND_PRODUCT_SERVICE_PORT:3000'
      - '9229:9229'
    depends_on:
      psql:
        condition: service_started
      prometheus:
        condition: service_healthy
      localstack:
        condition: service_healthy

  notifications:
    build: ./services/notifications
    container_name: notifications
    env_file:
      - .env
    ports:
      - '$BIND_NOTIFICATION_SERVICE_PORT:3001'
    depends_on:
      localstack:
        condition: service_healthy
      psql:
        condition: service_started

  psql:
    container_name: psql
    image: postgres:16
    environment:
      DATABASE_URL: $DATABASE_URL
    ports:
      - "$BIND_POSTGRES_PORT:5432"
    volumes:
      - ./psql:/var/lib/postgresql/data

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - $BIND_PROMETHEUS_PORT:9090
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=$LOCALSTASK_SERVICES
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "./localstack/init:/etc/localstack/init:Z"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD-SHELL", "awslocal sqs list-queues >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  psql:
